spring:
  application:
    name: s29624-TPO11
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    username: rose
    password: test
    url: jdbc:h2:file.:./db/links
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: PT1H
    web:
      locale: en
      locale-resolver: session

  app:
    base-url: http://localhost:8080
