
spring:
  application:
    name: s29624-TPO11
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    username: rose
    password: test
    url: jdbc:h2:file:./db/stored_links
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

app:
  base-url: http://localhost:8080